
name: BlockShuffle
version: ${version}
main: org.minimc.BlockShuffle.BlockShuffle
description: ${description}
api-version: 1.18
author: GSBRT

commands:
  blockshuffle:
    description: The main command for the BlockShuffle plugin.
    aliases: [bs]